version: '3.8'

services:
  auth_service:
    build: ./auth_service
    ports:
      - "5001:5000"
  user_service:
    build: ./user_service
    ports:
      - "5002:5000"
  data_service:
    build: ./data_service
    ports:
      - "5003:5000"